<?php

use yii\db\Migration;

class m160628_073723_kabupaten extends Migration
{
    public function up()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%kabupaten}}', [
            'NO_PROP' => $this->integer()->notNull(),
            'NO_KAB' => $this->integer()->notNull(),
            'NAMA_KAB' => $this->string(180)->notNull(),
            'KET' => $this->string(900),
        ], $tableOptions);

        $this->batchInsert('{{%kabupaten}}', ['NO_PROP', 'NO_KAB', 'NAMA_KAB'], [
                [11, 1, 'ACEH SELATAN'],
                [11, 2, 'ACEH TENGGARA'],
                [11, 3, 'ACEH TIMUR'],
                [11, 4, 'ACEH TENGAH'],
                [11, 5, 'ACEH BARAT'],
                [11, 6, 'ACEH BESAR'],
                [11, 7, 'PIDIE'],
                [11, 8, 'ACEH UTARA'],
                [11, 9, 'SIMEULUE'],
                [11, 10, 'ACEH SINGKIL'],
                [11, 11, 'BIREUEN'],
                [11, 12, 'ACEH BARAT DAYA'],
                [11, 13, 'GAYO LUES'],
                [11, 14, 'ACEH JAYA'],
                [11, 15, 'NAGAN RAYA'],
                [11, 16, 'ACEH TAMIANG'],
                [11, 17, 'BENER MERIAH'],
                [11, 18, 'PIDIE JAYA'],
                [11, 71, 'KOTA BANDA ACEH'],
                [11, 72, 'KOTA SABANG'],
                [11, 73, 'KOTA LHOKSEUMAWE'],
                [11, 74, 'KOTA LANGSA'],
                [11, 75, 'KOTA SUBULUSSALAM'],
                [12, 1, 'TAPANULI TENGAH'],
                [12, 2, 'TAPANULI UTARA'],
                [12, 3, 'TAPANULI SELATAN'],
                [12, 4, 'NIAS'],
                [12, 5, 'LANGKAT'],
                [12, 6, 'KARO'],
                [12, 7, 'DELI SERDANG'],
                [12, 8, 'SIMALUNGUN'],
                [12, 9, 'ASAHAN'],
                [12, 10, 'LABUHANBATU'],
                [12, 11, 'DAIRI'],
                [12, 12, 'TOBA SAMOSIR'],
                [12, 13, 'MANDAILING NATAL'],
                [12, 14, 'NIAS SELATAN'],
                [12, 15, 'PAKPAK BHARAT'],
                [12, 16, 'HUMBANG HASUNDUTAN'],
                [12, 17, 'SAMOSIR'],
                [12, 18, 'SERDANG BEDAGAI'],
                [12, 19, 'BATU BARA'],
                [12, 20, 'PADANG LAWAS UTARA'],
                [12, 21, 'PADANG LAWAS'],
                [12, 22, 'LABUHANBATU SELATAN'],
                [12, 23, 'LABUHANBATU UTARA'],
                [12, 24, 'NIAS UTARA'],
                [12, 25, 'NIAS BARAT'],
                [12, 71, 'KOTA MEDAN'],
                [12, 72, 'KOTA PEMATANG SIANTAR'],
                [12, 73, 'KOTA SIBOLGA'],
                [12, 74, 'KOTA TANJUNG BALAI'],
                [12, 75, 'KOTA BINJAI'],
                [12, 76, 'KOTA TEBING TINGGI'],
                [12, 77, 'KOTA PADANGSIDIMPUAN'],
                [12, 78, 'KOTA GUNUNGSITOLI'],
                [13, 1, 'PESISIR SELATAN'],
                [13, 2, 'SOLOK'],
                [13, 3, 'SIJUNJUNG'],
                [13, 4, 'TANAH DATAR'],
                [13, 5, 'PADANG PARIAMAN'],
                [13, 6, 'AGAM'],
                [13, 7, 'LIMA PULUH KOTA'],
                [13, 8, 'PASAMAN'],
                [13, 9, 'KEPULAUAN MENTAWAI'],
                [13, 10, 'DHARMASRAYA'],
                [13, 11, 'SOLOK SELATAN'],
                [13, 12, 'PASAMAN BARAT'],
                [13, 71, 'KOTA PADANG'],
                [13, 72, 'KOTA SOLOK'],
                [13, 73, 'KOTA SAWAHLUNTO'],
                [13, 74, 'KOTA PADANG PANJANG'],
                [13, 75, 'KOTA BUKITTINGGI'],
                [13, 76, 'KOTA PAYAKUMBUH'],
                [13, 77, 'KOTA PARIAMAN'],
                [14, 1, 'KAMPAR'],
                [14, 2, 'INDRAGIRI HULU'],
                [14, 3, 'BENGKALIS'],
                [14, 4, 'INDRAGIRI HILIR'],
                [14, 5, 'PELALAWAN'],
                [14, 6, 'ROKAN HULU'],
                [14, 7, 'ROKAN HILIR'],
                [14, 8, 'SIAK'],
                [14, 9, 'KUANTAN SINGINGI'],
                [14, 10, 'KEPULAUAN MERANTI'],
                [14, 71, 'KOTA PEKANBARU'],
                [14, 72, 'KOTA DUMAI'],
                [15, 1, 'KERINCI'],
                [15, 2, 'MERANGIN'],
                [15, 3, 'SAROLANGUN'],
                [15, 4, 'BATANGHARI'],
                [15, 5, 'MUARO JAMBI'],
                [15, 6, 'TANJUNG JABUNG BARAT'],
                [15, 7, 'TANJUNG JABUNG TIMUR'],
                [15, 8, 'BUNGO'],
                [15, 9, 'TEBO'],
                [15, 71, 'KOTA JAMBI'],
                [15, 72, 'KOTA SUNGAI PENUH'],
                [16, 1, 'OGAN KOMERING ULU'],
                [16, 2, 'OGAN KOMERING ILIR'],
                [16, 3, 'MUARA ENIM'],
                [16, 4, 'LAHAT'],
                [16, 5, 'MUSI RAWAS'],
                [16, 6, 'MUSI BANYUASIN'],
                [16, 7, 'BANYUASIN'],
                [16, 8, 'OGAN KOMERING ULU TIMUR'],
                [16, 9, 'OGAN KOMERING ULU SELATAN'],
                [16, 10, 'OGAN ILIR'],
                [16, 11, 'EMPAT LAWANG'],
                [16, 12, 'PENUKAL ABAB LEMATANG ILIR'],
                [16, 13, 'MUSI RAWAS UTARA'],
                [16, 71, 'KOTA PALEMBANG'],
                [16, 72, 'KOTA PAGAR ALAM'],
                [16, 73, 'KOTA LUBUK LINGGAU'],
                [16, 74, 'KOTA PRABUMULIH'],
                [17, 1, 'BENGKULU SELATAN'],
                [17, 2, 'REJANG LEBONG'],
                [17, 3, 'BENGKULU UTARA'],
                [17, 4, 'KAUR'],
                [17, 5, 'SELUMA'],
                [17, 6, 'MUKO MUKO'],
                [17, 7, 'LEBONG'],
                [17, 8, 'KEPAHIANG'],
                [17, 9, 'BENGKULU TENGAH'],
                [17, 71, 'KOTA BENGKULU'],
                [18, 1, 'LAMPUNG SELATAN'],
                [18, 2, 'LAMPUNG TENGAH'],
                [18, 3, 'LAMPUNG UTARA'],
                [18, 4, 'LAMPUNG BARAT'],
                [18, 5, 'TULANG BAWANG'],
                [18, 6, 'TANGGAMUS'],
                [18, 7, 'LAMPUNG TIMUR'],
                [18, 8, 'WAY KANAN'],
                [18, 9, 'PESAWARAN'],
                [18, 10, 'PRINGSEWU'],
                [18, 11, 'MESUJI'],
                [18, 12, 'TULANG BAWANG BARAT'],
                [18, 13, 'PESISIR BARAT'],
                [18, 71, 'KOTA BANDAR LAMPUNG'],
                [18, 72, 'KOTA METRO'],
                [19, 1, 'BANGKA'],
                [19, 2, 'BELITUNG'],
                [19, 3, 'BANGKA SELATAN'],
                [19, 4, 'BANGKA TENGAH'],
                [19, 5, 'BANGKA BARAT'],
                [19, 6, 'BELITUNG TIMUR'],
                [19, 71, 'KOTA PANGKAL PINANG'],
                [21, 1, 'BINTAN'],
                [21, 2, 'KARIMUN'],
                [21, 3, 'NATUNA'],
                [21, 4, 'LINGGA'],
                [21, 5, 'KEPULAUAN ANAMBAS'],
                [21, 71, 'KOTA BATAM'],
                [21, 72, 'KOTA TANJUNG PINANG'],
                [31, 1, 'ADM. KEP. SERIBU'],
                [31, 71, 'KOTA ADM. JAKARTA PUSAT'],
                [31, 72, 'KOTA ADM. JAKARTA UTARA'],
                [31, 73, 'KOTA ADM. JAKARTA BARAT'],
                [31, 74, 'KOTA ADM. JAKARTA SELATAN'],
                [31, 75, 'KOTA ADM. JAKARTA TIMUR'],
                [32, 1, 'BOGOR'],
                [32, 2, 'SUKABUMI'],
                [32, 3, 'CIANJUR'],
                [32, 4, 'BANDUNG'],
                [32, 5, 'GARUT'],
                [32, 6, 'TASIKMALAYA'],
                [32, 7, 'CIAMIS'],
                [32, 8, 'KUNINGAN'],
                [32, 9, 'CIREBON'],
                [32, 10, 'MAJALENGKA'],
                [32, 11, 'SUMEDANG'],
                [32, 12, 'INDRAMAYU'],
                [32, 13, 'SUBANG'],
                [32, 14, 'PURWAKARTA'],
                [32, 15, 'KARAWANG'],
                [32, 16, 'BEKASI'],
                [32, 17, 'BANDUNG BARAT'],
                [32, 18, 'PANGANDARAN'],
                [32, 71, 'KOTA BOGOR'],
                [32, 72, 'KOTA SUKABUMI'],
                [32, 73, 'KOTA BANDUNG'],
                [32, 74, 'KOTA CIREBON'],
                [32, 75, 'KOTA BEKASI'],
                [32, 76, 'KOTA DEPOK'],
                [32, 77, 'KOTA CIMAHI'],
                [32, 78, 'KOTA TASIKMALAYA'],
                [32, 79, 'KOTA BANJAR'],
                [33, 1, 'CILACAP'],
                [33, 2, 'BANYUMAS'],
                [33, 3, 'PURBALINGGA'],
                [33, 4, 'BANJARNEGARA'],
                [33, 5, 'KEBUMEN'],
                [33, 6, 'PURWOREJO'],
                [33, 7, 'WONOSOBO'],
                [33, 8, 'MAGELANG'],
                [33, 9, 'BOYOLALI'],
                [33, 10, 'KLATEN'],
                [33, 11, 'SUKOHARJO'],
                [33, 12, 'WONOGIRI'],
                [33, 13, 'KARANGANYAR'],
                [33, 14, 'SRAGEN'],
                [33, 15, 'GROBOGAN'],
                [33, 16, 'BLORA'],
                [33, 17, 'REMBANG'],
                [33, 18, 'PATI'],
                [33, 19, 'KUDUS'],
                [33, 20, 'JEPARA'],
                [33, 21, 'DEMAK'],
                [33, 22, 'SEMARANG'],
                [33, 23, 'TEMANGGUNG'],
                [33, 24, 'KENDAL'],
                [33, 25, 'BATANG'],
                [33, 26, 'PEKALONGAN'],
                [33, 27, 'PEMALANG'],
                [33, 28, 'TEGAL'],
                [33, 29, 'BREBES'],
                [33, 71, 'KOTA MAGELANG'],
                [33, 72, 'KOTA SURAKARTA'],
                [33, 73, 'KOTA SALATIGA'],
                [33, 74, 'KOTA SEMARANG'],
                [33, 75, 'KOTA PEKALONGAN'],
                [33, 76, 'KOTA TEGAL'],
                [34, 1, 'KULON PROGO'],
                [34, 2, 'BANTUL'],
                [34, 3, 'GUNUNG KIDUL'],
                [34, 4, 'SLEMAN'],
                [34, 71, 'KOTA YOGYAKARTA'],
                [35, 1, 'PACITAN'],
                [35, 2, 'PONOROGO'],
                [35, 3, 'TRENGGALEK'],
                [35, 4, 'TULUNGAGUNG'],
                [35, 5, 'BLITAR'],
                [35, 6, 'KEDIRI'],
                [35, 7, 'MALANG'],
                [35, 8, 'LUMAJANG'],
                [35, 9, 'JEMBER'],
                [35, 10, 'BANYUWANGI'],
                [35, 11, 'BONDOWOSO'],
                [35, 12, 'SITUBONDO'],
                [35, 13, 'PROBOLINGGO'],
                [35, 14, 'PASURUAN'],
                [35, 15, 'SIDOARJO'],
                [35, 16, 'MOJOKERTO'],
                [35, 17, 'JOMBANG'],
                [35, 18, 'NGANJUK'],
                [35, 19, 'MADIUN'],
                [35, 20, 'MAGETAN'],
                [35, 21, 'NGAWI'],
                [35, 22, 'BOJONEGORO'],
                [35, 23, 'TUBAN'],
                [35, 24, 'LAMONGAN'],
                [35, 25, 'GRESIK'],
                [35, 26, 'BANGKALAN'],
                [35, 27, 'SAMPANG'],
                [35, 28, 'PAMEKASAN'],
                [35, 29, 'SUMENEP'],
                [35, 71, 'KOTA KEDIRI'],
                [35, 72, 'KOTA BLITAR'],
                [35, 73, 'KOTA MALANG'],
                [35, 74, 'KOTA PROBOLINGGO'],
                [35, 75, 'KOTA PASURUAN'],
                [35, 76, 'KOTA MOJOKERTO'],
                [35, 77, 'KOTA MADIUN'],
                [35, 78, 'KOTA SURABAYA'],
                [35, 79, 'KOTA BATU'],
                [36, 1, 'PANDEGLANG'],
                [36, 2, 'LEBAK'],
                [36, 3, 'TANGERANG'],
                [36, 4, 'SERANG'],
                [36, 71, 'KOTA TANGERANG'],
                [36, 72, 'KOTA CILEGON'],
                [36, 73, 'KOTA SERANG'],
                [36, 74, 'KOTA TANGERANG SELATAN'],
                [51, 1, 'JEMBRANA'],
                [51, 2, 'TABANAN'],
                [51, 3, 'BADUNG'],
                [51, 4, 'GIANYAR'],
                [51, 5, 'KLUNGKUNG'],
                [51, 6, 'BANGLI'],
                [51, 7, 'KARANGASEM'],
                [51, 8, 'BULELENG'],
                [51, 71, 'KOTA DENPASAR'],
                [52, 1, 'LOMBOK BARAT'],
                [52, 2, 'LOMBOK TENGAH'],
                [52, 3, 'LOMBOK TIMUR'],
                [52, 4, 'SUMBAWA'],
                [52, 5, 'DOMPU'],
                [52, 6, 'BIMA'],
                [52, 7, 'SUMBAWA BARAT'],
                [52, 8, 'LOMBOK UTARA'],
                [52, 71, 'KOTA MATARAM'],
                [52, 72, 'KOTA BIMA'],
                [53, 1, 'KUPANG'],
                [53, 2, 'KAB TIMOR TENGAH SELATAN'],
                [53, 3, 'TIMOR TENGAH UTARA'],
                [53, 4, 'BELU'],
                [53, 5, 'ALOR'],
                [53, 6, 'FLORES TIMUR'],
                [53, 7, 'SIKKA'],
                [53, 8, 'ENDE'],
                [53, 9, 'NGADA'],
                [53, 10, 'MANGGARAI'],
                [53, 11, 'SUMBA TIMUR'],
                [53, 12, 'SUMBA BARAT'],
                [53, 13, 'LEMBATA'],
                [53, 14, 'ROTE NDAO'],
                [53, 15, 'MANGGARAI BARAT'],
                [53, 16, 'NAGEKEO'],
                [53, 17, 'SUMBA TENGAH'],
                [53, 18, 'SUMBA BARAT DAYA'],
                [53, 19, 'MANGGARAI TIMUR'],
                [53, 20, 'SABU RAIJUA'],
                [53, 21, 'MALAKA'],
                [53, 71, 'KOTA KUPANG'],
                [61, 1, 'SAMBAS'],
                [61, 2, 'MEMPAWAH'],
                [61, 3, 'SANGGAU'],
                [61, 4, 'KETAPANG'],
                [61, 5, 'SINTANG'],
                [61, 6, 'KAPUAS HULU'],
                [61, 7, 'BENGKAYANG'],
                [61, 8, 'LANDAK'],
                [61, 9, 'SEKADAU'],
                [61, 10, 'MELAWI'],
                [61, 11, 'KAYONG UTARA'],
                [61, 12, 'KUBU RAYA'],
                [61, 71, 'KOTA PONTIANAK'],
                [61, 72, 'KOTA SINGKAWANG'],
                [62, 1, 'KOTAWARINGIN BARAT'],
                [62, 2, 'KOTAWARINGIN TIMUR'],
                [62, 3, 'KAPUAS'],
                [62, 4, 'BARITO SELATAN'],
                [62, 5, 'BARITO UTARA'],
                [62, 6, 'KATINGAN'],
                [62, 7, 'SERUYAN'],
                [62, 8, 'SUKAMARA'],
                [62, 9, 'LAMANDAU'],
                [62, 10, 'GUNUNG MAS'],
                [62, 11, 'PULANG PISAU'],
                [62, 12, 'MURUNG RAYA'],
                [62, 13, 'BARITO TIMUR'],
                [62, 71, 'KOTA PALANGKARAYA'],
                [63, 1, 'TANAH LAUT'],
                [63, 2, 'KOTABARU'],
                [63, 3, 'BANJAR'],
                [63, 4, 'BARITO KUALA'],
                [63, 5, 'TAPIN'],
                [63, 6, 'HULU SUNGAI SELATAN'],
                [63, 7, 'HULU SUNGAI TENGAH'],
                [63, 8, 'HULU SUNGAI UTARA'],
                [63, 9, 'TABALONG'],
                [63, 10, 'TANAH BUMBU'],
                [63, 11, 'BALANGAN'],
                [63, 71, 'KOTA BANJARMASIN'],
                [63, 72, 'KOTA BANJARBARU'],
                [64, 1, 'PASER'],
                [64, 2, 'KUTAI KARTANEGARA'],
                [64, 3, 'BERAU'],
                [64, 7, 'KUTAI BARAT'],
                [64, 8, 'KUTAI TIMUR'],
                [64, 9, 'PENAJAM PASER UTARA'],
                [64, 11, 'MAHAKAM ULU'],
                [64, 71, 'KOTA BALIKPAPAN'],
                [64, 72, 'KOTA SAMARINDA'],
                [64, 74, 'KOTA BONTANG'],
                [65, 1, 'BULUNGAN'],
                [65, 2, 'MALINAU'],
                [65, 3, 'NUNUKAN'],
                [65, 4, 'TANA TIDUNG'],
                [65, 71, 'KOTA TARAKAN'],
                [71, 1, 'BOLAANG MONGONDOW'],
                [71, 2, 'MINAHASA'],
                [71, 3, 'KEPULAUAN SANGIHE'],
                [71, 4, 'KEPULAUAN TALAUD'],
                [71, 5, 'MINAHASA SELATAN'],
                [71, 6, 'MINAHASA UTARA'],
                [71, 7, 'MINAHASA TENGGARA'],
                [71, 8, 'BOLAANG MONGONDOW UTARA'],
                [71, 9, 'KEP. SIAU TAGULANDANG BIARO'],
                [71, 10, 'BOLAANG MONGONDOW TIMUR'],
                [71, 11, 'BOLAANG MONGONDOW SELATAN'],
                [71, 71, 'KOTA MANADO'],
                [71, 72, 'KOTA BITUNG'],
                [71, 73, 'KOTA TOMOHON'],
                [71, 74, 'KOTA KOTAMOBAGU'],
                [72, 1, 'BANGGAI'],
                [72, 2, 'POSO'],
                [72, 3, 'DONGGALA'],
                [72, 4, 'TOLI TOLI'],
                [72, 5, 'BUOL'],
                [72, 6, 'MOROWALI'],
                [72, 7, 'BANGGAI KEPULAUAN'],
                [72, 8, 'PARIGI MOUTONG'],
                [72, 9, 'TOJO UNA UNA'],
                [72, 10, 'SIGI'],
                [72, 11, 'BANGGAI LAUT'],
                [72, 12, 'MOROWALI UTARA'],
                [72, 71, 'KOTA PALU'],
                [73, 1, 'KEPULAUAN SELAYAR'],
                [73, 2, 'BULUKUMBA'],
                [73, 3, 'BANTAENG'],
                [73, 4, 'JENEPONTO'],
                [73, 5, 'TAKALAR'],
                [73, 6, 'GOWA'],
                [73, 7, 'SINJAI'],
                [73, 8, 'BONE'],
                [73, 9, 'MAROS'],
                [73, 10, 'PANGKAJENE KEPULAUAN'],
                [73, 11, 'BARRU'],
                [73, 12, 'SOPPENG'],
                [73, 13, 'WAJO'],
                [73, 14, 'SIDENRENG RAPPANG'],
                [73, 15, 'PINRANG'],
                [73, 16, 'ENREKANG'],
                [73, 17, 'LUWU'],
                [73, 18, 'TANA TORAJA'],
                [73, 22, 'LUWU UTARA'],
                [73, 24, 'LUWU TIMUR'],
                [73, 26, 'TORAJA UTARA'],
                [73, 71, 'KOTA MAKASSAR'],
                [73, 72, 'KOTA PARE PARE'],
                [73, 73, 'KOTA PALOPO'],
                [74, 1, 'KOLAKA'],
                [74, 2, 'KONAWE'],
                [74, 3, 'MUNA'],
                [74, 4, 'BUTON'],
                [74, 5, 'KONAWE SELATAN'],
                [74, 6, 'BOMBANA'],
                [74, 7, 'WAKATOBI'],
                [74, 8, 'KOLAKA UTARA'],
                [74, 9, 'KONAWE UTARA'],
                [74, 10, 'BUTON UTARA'],
                [74, 11, 'KOLAKA TIMUR'],
                [74, 12, 'KONAWE KEPULAUAN'],
                [74, 13, 'MUNA BARAT'],
                [74, 14, 'BUTON TENGAH'],
                [74, 15, 'BUTON SELATAN'],
                [74, 71, 'KOTA KENDARI'],
                [74, 72, 'KOTA BAU BAU'],
                [75, 1, 'GORONTALO'],
                [75, 2, 'BOALEMO'],
                [75, 3, 'BONE BOLANGO'],
                [75, 4, 'PAHUWATO'],
                [75, 5, 'GORONTALO UTARA'],
                [75, 71, 'KOTA GORONTALO'],
                [76, 1, 'MAMUJU UTARA'],
                [76, 2, 'MAMUJU'],
                [76, 3, 'MAMASA'],
                [76, 4, 'POLEWALI MANDAR'],
                [76, 5, 'MAJENE'],
                [76, 6, 'MAMUJU TENGAH'],
                [81, 1, 'MALUKU TENGAH'],
                [81, 2, 'MALUKU TENGGARA'],
                [81, 3, 'KAB MALUKU TENGGARA BARAT'],
                [81, 4, 'BURU'],
                [81, 5, 'SERAM BAGIAN TIMUR'],
                [81, 6, 'SERAM BAGIAN BARAT'],
                [81, 7, 'KEPULAUAN ARU'],
                [81, 8, 'MALUKU BARAT DAYA'],
                [81, 9, 'BURU SELATAN'],
                [81, 71, 'KOTA AMBON'],
                [81, 72, 'KOTA TUAL'],
                [82, 1, 'HALMAHERA BARAT'],
                [82, 2, 'HALMAHERA TENGAH'],
                [82, 3, 'HALMAHERA UTARA'],
                [82, 4, 'HALMAHERA SELATAN'],
                [82, 5, 'KEPULAUAN SULA'],
                [82, 6, 'HALMAHERA TIMUR'],
                [82, 7, 'PULAU MOROTAI'],
                [82, 8, 'PULAU TALIABU'],
                [82, 71, 'KOTA TERNATE'],
                [82, 72, 'KOTA TIDORE KEPULAUAN'],
                [91, 1, 'MERAUKE'],
                [91, 2, 'JAYAWIJAYA'],
                [91, 3, 'JAYAPURA'],
                [91, 4, 'NABIRE'],
                [91, 5, 'KEPULAUAN YAPEN'],
                [91, 6, 'BIAK NUMFOR'],
                [91, 7, 'PUNCAK JAYA'],
                [91, 8, 'PANIAI'],
                [91, 9, 'MIMIKA'],
                [91, 10, 'SARMI'],
                [91, 11, 'KEEROM'],
                [91, 12, 'KAB PEGUNUNGAN BINTANG'],
                [91, 13, 'YAHUKIMO'],
                [91, 14, 'TOLIKARA'],
                [91, 15, 'WAROPEN'],
                [91, 16, 'BOVEN DIGOEL'],
                [91, 17, 'MAPPI'],
                [91, 18, 'ASMAT'],
                [91, 19, 'SUPIORI'],
                [91, 20, 'MAMBERAMO RAYA'],
                [91, 21, 'MAMBERAMO TENGAH'],
                [91, 22, 'YALIMO'],
                [91, 23, 'LANNY JAYA'],
                [91, 24, 'NDUGA'],
                [91, 25, 'PUNCAK'],
                [91, 26, 'DOGIYAI'],
                [91, 27, 'INTAN JAYA'],
                [91, 28, 'DEIYAI'],
                [91, 71, 'KOTA JAYAPURA'],
                [92, 1, 'SORONG'],
                [92, 2, 'MANOKWARI'],
                [92, 3, 'FAK FAK'],
                [92, 4, 'SORONG SELATAN'],
                [92, 5, 'RAJA AMPAT'],
                [92, 6, 'TELUK BINTUNI'],
                [92, 7, 'TELUK WONDAMA'],
                [92, 8, 'KAIMANA'],
                [92, 9, 'TAMBRAUW'],
                [92, 10, 'MAYBRAT'],
                [92, 11, 'MANOKWARI SELATAN'],
                [92, 12, 'PEGUNUNGAN ARFAK'],
                [92, 71, 'KOTA SORONG'],
            ]);
    }

    public function down()
    {
        $this->dropTable('{{%kabupaten}}');

        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
